import '../globals.css';
import { Poppins } from 'next/font/google';
import React, { SVGProps } from 'react';
import styles from './styles.module.css';

const poppins = Poppins({
  weight: ['100', '300', '400', '500', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Consulta Predio',
  description: 'Generated by create next app',
};

export default function ConsultaLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className={`flex flex-col ${styles.bgCons}`}>{children}</section>
  );
}
