import './globals.css';
import { Poppins } from 'next/font/google';
import React, { SVGProps } from 'react';

const poppins = Poppins({
  weight: ['100', '300', '400', '500', '700', '800', '900'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
});

export const metadata = {
  title: 'Pago En Linea Predial',
  description: 'Generated by create next app',
};

const Blob = (props: SVGProps<SVGSVGElement>) => (
    <svg
        width={1823}
        height={1741}
        viewBox="0 0 1823 1741"
        fill="none"
        xmlns="http://www.w3.org/2000/svg"
        {...props}
    >
        <g clipPath="url(#clip0_230_2)">
            <mask
                id="mask0_230_2"
                style={{
                    maskType: "luminance",
                }}
                maskUnits="userSpaceOnUse"
                x={-164}
                y={-412}
                width={1471}
                height={1688}
            >
                <path
                    d="M1183.15 140.18C1150.06 380.074 1179.48 612.211 1271.41 836.592C1363.34 1060.97 1272.61 1157.16 999.234 1125.17C725.856 1093.17 527.476 1122.13 404.093 1212.07C280.71 1302 164.177 1295.6 54.4947 1192.86C-55.1876 1090.11 -102.174 973.853 -86.464 844.078C-70.7541 714.303 -84.3211 589.624 -127.165 470.041C-170.009 350.458 -175.162 179.358 -142.626 -43.2591C-110.09 -265.876 15.1488 -386.593 233.091 -405.409C451.033 -424.226 672.136 -397.972 896.399 -326.648C1120.66 -255.324 1216.25 -99.7145 1183.15 140.18Z"
                    fill="white"
                />
            </mask>
            <g mask="url(#mask0_230_2)">
                <path
                    d="M1183.15 140.18C1150.06 380.074 1179.48 612.211 1271.41 836.592C1363.34 1060.97 1272.61 1157.16 999.234 1125.17C725.856 1093.17 527.476 1122.13 404.093 1212.07C280.71 1302 164.177 1295.6 54.4947 1192.86C-55.1876 1090.11 -102.174 973.853 -86.464 844.078C-70.7541 714.303 -84.3211 589.624 -127.165 470.041C-170.009 350.458 -175.162 179.358 -142.626 -43.2591C-110.09 -265.876 15.1488 -386.593 233.091 -405.409C451.033 -424.226 672.136 -397.972 896.399 -326.648C1120.66 -255.324 1216.25 -99.7145 1183.15 140.18Z"
                    fill="url(#paint0_linear_230_2)"
                />
            </g>
        </g>
        <defs>
            <linearGradient
                id="paint0_linear_230_2"
                x1={-1042.17}
                y1={-36.9823}
                x2={-985.946}
                y2={-1756.44}
                gradientUnits="userSpaceOnUse"
            >
                <stop stopColor="#FFBD6F" />
                <stop offset={1} stopColor="#F76B1C" />
            </linearGradient>
            <clipPath id="clip0_230_2">
                <rect
                    width={1723}
                    height={1895}
                    fill="white"
                    transform="translate(-731.011 358.229) rotate(-43.1412)"
                />
            </clipPath>
        </defs>
    </svg>
);

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="es" className={`${poppins.className} h-full page-bg antialiased`}>
      {/*<Blob className="absolute top-0 -z20 w-full" />*/}

      <body className="flex h-full flex-col">{children}</body>
    </html>
  );
}
